// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-1:6722c8ee-1742-4d8f-9ec6-88d74452222e';
var aws_cognito_region = 'us-east-1';
var aws_mobile_analytics_app_id = '65e157f3dd7f4eed8f2618e80b349d9f';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = 'd06eb33e-79fd-4cfa-ac4a-2ad023a5b95a';
var aws_project_name = 'Servicios Tecnicos EEH';
var aws_project_region = 'us-east-1';
var aws_resource_name_prefix = 'serviciostecnicoseeh-mobilehub-1422398732';
var aws_sign_in_enabled = 'enable';
var aws_user_pools = 'enable';
var aws_user_pools_id = 'us-east-1_NoHqFSxNu';
var aws_user_pools_mfa_type = 'OFF';
var aws_user_pools_web_client_id = '3go0pktjvvo5cd0lavjjnpen7m';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
